# Generated by Django 6.0.2 on 2026-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('material', models.CharField(max_length=20)),
                ('proizvodstvo', models.CharField(max_length=50)),
                ('ves', models.FloatField()),
                ('tsvet', models.CharField(max_length=20)),
                ('dlina', models.FloatField()),
                ('shirina', models.FloatField()),
                ('visota', models.FloatField()),
            ],
        ),
    ]
