# Generated by Django 6.0.2 on 2026-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santech_pro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
