# Generated by Django 6.0.2 on 2026-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santech_pro_app', '0002_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='santehnick_tupe',
            field=models.CharField(choices=[(1, 'туалет'), (2, 'сантехниеа')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
